# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/beerlog',
                'doc_host': 'https://joaopcnogueira.github.io',
                'git_url': 'https://github.com/joaopcnogueira/beerlog',
                'lib_path': 'beerlog'},
  'syms': {'beerlog.core': {'beerlog.core.foo': ('core.html#foo', 'beerlog/core.py')}}}